# Generated by Django 2.2.9 on 2020-03-25 12:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_robots', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_revisit', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_language', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_rating', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_copyright', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_google_site_verification', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('news_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('short_description', models.TextField(blank=True, help_text='Short description shown on blogs listing page', null=True)),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_alt_text', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
